services:
  api:
    image: ghcr.io/adrianordp/pokemon_unite_analysis_api:latest
    container_name: pokemon-unite-api
    environment:
      - API_HOST=api
      - API_PORT=8050
    ports:
      - "8050:8050"

  dashboard:
    image: ghcr.io/adrianordp/pokemon_unite_analysis_dashboard:latest
    container_name: pokemon-unite-dashboard
    depends_on:
      - api
    environment:
      - API_HOST=api
      - API_PORT=8050
    ports:
      - "8501:8501"
